### ISSUE TITLE
Warning even if route settings are provided

### ISSUE THREAD

**Issue by mileswatson** [talbotp/serverless-apigateway-route-settings#1]
When I run "serverless package" or "serverless deploy", the extension throws the following warnings:

 - `Warning: No default Route Settings have been provided.`
 - `Warning: No Route settings have been provided.`

This is despite having included the following code in the `serverless.yml` file.
```
plugins:
  - serverless-apigateway-route-settings
custom:
  routeSettings:
    rateLimit: 10
    burstLimit: 5
    detailedMetricsEnabled: false
```

Curiously, the deployment seems to work as expected. I dug around a little bit, and found that the cloud formation code was correct. 

```
"HttpApiStage": {
  "Type": "AWS::ApiGatewayV2::Stage",
  "Properties": {
    "ApiId": {
      "Ref": "HttpApi"
    },
    "StageName": "$default",
    "AutoDeploy": true,
    "DefaultRouteSettings": {
      "DetailedMetricsEnabled": false,
      "ThrottlingBurstLimit": 5,
      "ThrottlingRateLimit": 10
    }
  }
},
```

The error is still thrown when overriding the settings for a specific function (and the corresponding cloud formation code is also correct).

**Comment by talbotp** [comment]
Hey @mileswatson Thanks for reporting this bug :slightly_smiling_face: I will take a look into this and try and fix it :+1:

**Comment by talbotp** [comment]
This was fixed in this [commit](https://github.com/talbotp/serverless-apigateway-route-settings/commit/ca11edcd2033b2cb77252b1d5b1ec3678686252b) and released in version [1.0.0](https://www.npmjs.com/package/serverless-apigateway-route-settings/v/1.0.0).

I've kept the "Warning: No Route settings have been provided." warning but reworded it to "Warning: No RouteSettings have been provided to override the DefaultRouteSettings.". Just means that no route specific routesettings are have been added to the serverless.yml to override. But i've fixed the DefaultRouteSettings warning. 

Thanks again :slightly_smiling_face:

**Comment by mileswatson** [comment]
I'm still getting `Warning: No RouteSettings have been provided to override the DefaultRouteSettings.`? This is when I have provided `routeSettings` under `custom`, including when I have no httpApi functions in `serverless.yml`.

**Comment by talbotp** [comment]
I'm thinking that is the expected behaviour. The DefaultRouteSettings are specified in the custom attribute, and will apply to all of the Routes in your Stage. However, the plugin allows you to override the DefaultRouteSettings (or account level settings) by specifying routeSettings under the httpApi event attribute, and those will be used only for that specific Route. 

So that warning message is just to let people know that no RouteSettings have been applied at the Route level. I wonder if it would be more clear to call the custom attribute defaultRouteSettings, and at the route level call it routeSettings, just to make it more obvious for new users? 🙂 

This [gist](https://gist.github.com/talbotp/20e7e6606e919d88ad6a502b141deefb) shows the difference 👍
